# Data Preprocessing of Business Funding Data in Nigeria

## Objective
The objective of this analysis is to clean, preprocess, and transform the Business Funding Data dataset as provided in the deep_tech program to make it suitable for further exploratory and predictive analysis. The preprocessing steps focus on handling missing values, duplicates, outliers, and transforming variables into analysis-ready formats.

# Installation & importing Liberies

In [1]:
# installation
!pip install pandas
!pip install numpy
!pip install scikit-learn

Requirement already satisfied: pandas in c:\users\bdm2\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\bdm2\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bdm2\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\bdm2\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\bdm2\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\bdm2\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in c:\users\bdm2\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: scikit-learn in c:\users\bdm2\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\bdm2\anaconda3\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\bdm2\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\bdm2\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\bdm2\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [24]:
#import Liberaries
import pandas as pd
import numpy as np

# Load Dataset (Code)

In [25]:
# Using the encoding='ISO-8859-1' to read the CSV file because it threw some errors because it was to read utf-8 encoding which didn't work
df = pd.read_csv('C:\\Users\\BDM2\\Downloads\\DSN\\Business Funding Data.csv', encoding='ISO-8859-1')
df.head(10)

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,NaN,2024-03-14T01:00:00+01:00,NaN,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaN,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaN,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaN,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaN,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-18T02:00:00+02:00,2024-04-24T02:00:00+02:00,Series B,series_b,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16T02:00:00+02:00,2024-04-16T02:00:00+02:00,NaN,NaN,"[""debt_financing""]",runwaygrowth.com,1.0,$40 million,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,NaN,2024-08-07T02:00:00+02:00,Series I,series_i,"[""series_i"", ""venture""]",NaN,NaN,$685 million,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,NaN,2024-07-08T02:00:00+02:00,NaN,NaN,[],damachotelsandresorts.com,1.0,$50mn,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,NaN,2024-04-18T02:00:00+02:00,NaN,NaN,[],NaN,NaN,AU$10.7M,6865000,https://www.biometricupdate.com/202404/ey-secu...

# Initial Data Exploration (Code)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             6 non-null      object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  13 non-null     object
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
 10  Source Urls                26 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB

In [27]:
df.describe()

       Investors Count  Amount Normalized
count        13.000000       2.600000e+01
mean          1.846154       2.264687e+08
std           2.230327       5.383239e+08
min           1.000000       1.600000e+06
25%           1.000000       4.685750e+06
50%           1.000000       1.160000e+07
75%           1.000000       4.750000e+07
max           9.000000       2.000000e+09

In [28]:
df.shape

(26, 11)

# Initial Exploration
- The dataset has 26 rows and 11 columns originally.
- Several columns contain missing values, especially `Effective date`, `Financing Type`, `Investors`, and `Investors Count`.
- Some columns are unnecessary for analysis and can be dropped (e.g., `Source Urls`, `Effective date`).

In [29]:
if 'Source Urls' in df.columns:
	df.drop(columns=['Source Urls'], inplace=True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             6 non-null      object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  13 non-null     object
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
dtypes: float64(1), int64(1), object(8)
memory usage: 2.2+ KB

In [31]:
df['Effective date'].unique()

array([nan, '2024-04-18T02:00:00+02:00', '2024-04-16T02:00:00+02:00',
       '2024-06-20T02:00:00+02:00', '2024-04-24T02:00:00+02:00',
       '2024-06-26T02:00:00+02:00', '2024-06-27T02:00:00+02:00'],
      dtype=object)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Website Domain             26 non-null     object
 1   Effective date             6 non-null      object
 2   Found At                   26 non-null     object
 3   Financing Type             8 non-null      object
 4   Financing Type Normalized  8 non-null      object
 5   Categories                 26 non-null     object
 6   Investors                  13 non-null     object
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object
 9   Amount Normalized          26 non-null     int64
dtypes: float64(1), int64(1), object(8)
memory usage: 2.2+ KB

# Handling Duplicates

In [33]:
duplicates = df.duplicated().sum()
print(f"number of duplicate rows: {duplicates}")

number of duplicate rows: 0

In [34]:
df['Financing Type Normalized'].unique()

array([nan, 'series_b', 'series_i', 'seed', 'series_a2', 'series_a'],
      dtype=object)

In [35]:
if 'Financing Type Normalized' in df.columns:
	df.drop(columns=['Financing Type Normalized'], inplace=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Website Domain     26 non-null     object
 1   Effective date     6 non-null      object
 2   Found At           26 non-null     object
 3   Financing Type     8 non-null      object
 4   Categories         26 non-null     object
 5   Investors          13 non-null     object
 6   Investors Count    13 non-null     float64
 7   Amount             26 non-null     object
 8   Amount Normalized  26 non-null     int64
dtypes: float64(1), int64(1), object(7)
memory usage: 2.0+ KB

In [37]:
if 'Financing Type' in df.columns:
    df.drop(columns=['Financing Type'], inplace=True)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Website Domain     26 non-null     object
 1   Effective date     6 non-null      object
 2   Found At           26 non-null     object
 3   Categories         26 non-null     object
 4   Investors          13 non-null     object
 5   Investors Count    13 non-null     float64
 6   Amount             26 non-null     object
 7   Amount Normalized  26 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.8+ KB

In [39]:
# Check unique values in Investors
print("Unique Investors values:")
print(df['Investors'].unique())

# Check number of nulls
print("\nNumber of nulls in Investors:", df['Investors'].isnull().sum())

# Check unique values in Investors Count
print("\nUnique Investors Count values:")
print(df['Investors Count'].unique())

# Number of nulls
print("\nNumber of nulls in Investors Count:", df['Investors Count'].isnull().sum())

Unique Investors values:
[nan
 'avivainvestors.com, lloydsbankinggroup.com, santander.co.uk, swip.com, cibc.com, societegenerale.com, natwest.us, rabobank.com, mufg.jp'
 'stackcapitalgroup.com' 'chevychasetrust.com'
 'alantra.com, blueearth.capital' 'runwaygrowth.com'
 'damachotelsandresorts.com' 'surocap.com' 'eib.org' 'vistaragrowth.com'
 'accelia.vc' 'edc.ca, desjardinscapital.com, fondsftq.com' 'cibc.com'
 'inovia.vc']

Number of nulls in Investors: 13

Unique Investors Count values:
[nan  9.  1.  2.  3.]

Number of nulls in Investors Count: 13

In [40]:
df['Investors'] = df['Investors'].fillna('Unknown')
df['Investors Count'] = df['Investors Count'].fillna(0)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Website Domain     26 non-null     object
 1   Effective date     6 non-null      object
 2   Found At           26 non-null     object
 3   Categories         26 non-null     object
 4   Investors          26 non-null     object
 5   Investors Count    26 non-null     float64
 6   Amount             26 non-null     object
 7   Amount Normalized  26 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.8+ KB

In [44]:
df.isnull().sum()

Website Domain        0
Effective date       20
Found At              0
Categories            0
Investors             0
Investors Count       0
Amount                0
Amount Normalized     0
dtype: int64

In [45]:
if 'Effective date' in df.columns:
    df.drop(columns=['Effective date'], inplace=True)

In [46]:
df.isnull().sum()

Website Domain       0
Found At             0
Categories           0
Investors            0
Investors Count      0
Amount               0
Amount Normalized    0
dtype: int64

In [47]:
df['Found At'] = pd.to_datetime(df['Found At'], errors='coerce')

In [48]:
df['Found At'].unique()

<DatetimeArray>
['2024-03-14 01:00:00+01:00', 'NaT', '2024-03-26 01:00:00+01:00']
Length: 3, dtype: datetime64[ns, UTC+01:00]

In [49]:
median_date = df['Found At'].median()
df['Found At'].fillna(median_date, inplace=True)

In [50]:
df['Found At'].unique()

<DatetimeArray>
['2024-03-14 01:00:00+01:00', '2024-03-20 01:00:00+01:00',
 '2024-03-26 01:00:00+01:00']
Length: 3, dtype: datetime64[ns, UTC+01:00]

In [51]:
df['Year'] = df['Found At'].dt.year
df['Month'] = df['Found At'].dt.month

In [52]:
def classify_funding(amount):
    if amount < 10_000_000:
        return 'Small'
    elif amount < 100_000_000:
        return 'Medium'
    else:
        return 'Large'

df['Funding Size'] = df['Amount Normalized'].apply(classify_funding)

In [53]:
df['Investors'] = df['Investors'].fillna('Unknown')
df['Investor List'] = df['Investors'].apply(lambda x: x.split(', ') if x != 'Unknown' else [])
df['Calculated Investor Count'] = df['Investor List'].apply(len)

In [54]:
df['Investors Count'] = df['Investors Count'].fillna(0)
df['Investor Density'] = df['Amount Normalized'] / (df['Investors Count'] + 1)

In [55]:
df['Categories'] = df['Categories'].apply(eval)
df['Category Count'] = df['Categories'].apply(len)
df['Primary Category'] = df['Categories'].apply(lambda x: x[0] if len(x) > 0 else 'Unknown')

In [56]:
import ast

def safe_eval(val):
    try:
        return ast.literal_eval(val)
    except:
        return [val] if isinstance(val, str) else []

df['Categories'] = df['Categories'].apply(safe_eval)

In [57]:
df.isnull().sum()

Website Domain               0
Found At                     0
Categories                   0
Investors                    0
Investors Count              0
Amount                       0
Amount Normalized            0
Year                         0
Month                        0
Funding Size                 0
Investor List                0
Calculated Investor Count    0
Investor Density             0
Category Count               0
Primary Category             0
dtype: int64

In [58]:
df.dtypes

Website Domain                                  object
Found At                     datetime64[ns, UTC+01:00]
Categories                                      object
Investors                                       object
Investors Count                                float64
Amount                                          object
Amount Normalized                                int64
Year                                             int32
Month                                            int32
Funding Size                                    object
Investor List                                   object
Calculated Investor Count                        int64
Investor Density                               float64
Category Count                                   int64
Primary Category                                object
dtype: object

In [62]:
# Full Enhanced Dataset Export

# Optional: select columns you want to keep in the new sheet
columns_to_keep = [
    'Website Domain',
    'Categories',
    'Category Count',
    'Primary Category',
    'Investors',
    'Investor List',
    'Calculated Investor Count',
    'Investors Count',
    'Investor Density',
    'Amount',
    'Amount Normalized',
    'Funding Size',
    'Found At',
    'Year',
    'Month'
]

# Create a new DataFrame with selected columns
enhanced_df = df[columns_to_keep]

# Export to CSV
enhanced_df.to_csv('Business_Funding_Data_Enhanced.csv', index=False)

print("Enhanced dataset saved as CSV")

Enhanced dataset saved as CSV